# Generated by Django 3.2 on 2023-12-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("texteditor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="room_name",
            new_name="name",
        ),
    ]
