# Generated by Django 3.2 on 2023-12-04 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import texteditor.models
import texteditor.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("texteditor", "0002_rename_room_name_room_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "note",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=texteditor.storage.PrivateMediaStorage,
                        upload_to=texteditor.models.note_upload_to,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
