# Generated by Django 3.2 on 2023-12-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("texteditor", "0003_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="note",
            new_name="file",
        ),
    ]
