# Generated by Django 3.2 on 2023-12-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("texteditor", "0004_rename_note_note_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="texteditor.room",
            ),
        ),
    ]
