# Generated by Django 3.2 on 2024-02-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("texteditor", "0006_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="parent_folder_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
