# Generated by Django 3.2 on 2024-02-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("texteditor", "0007_folder_parent_folder_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="texteditor.folder",
            ),
        ),
    ]
