# Generated by Django 3.2 on 2024-02-16 07:06

from django.db import migrations, models

import texteditor.models


class Migration(migrations.Migration):

    dependencies = [
        ("texteditor", "0008_note_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="token",
            field=models.CharField(default=texteditor.models.get_token, max_length=100),
        ),
    ]
