# Generated by Django 3.2 on 2024-02-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("texteditor", "0009_folder_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
