# Generated by Django 3.2 on 2024-02-16 09:07

from django.db import migrations, models

import texteditor.models


class Migration(migrations.Migration):

    dependencies = [
        ("texteditor", "0010_auto_20240216_0825"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="token",
            field=models.CharField(default=texteditor.models.get_token, max_length=100),
        ),
    ]
