# Generated by Django 3.2 on 2024-06-25 05:36

from django.db import migrations, models


def populate_index(apps, schema_editor):
    Folder = apps.get_model("texteditor", "Folder")
    Note = apps.get_model("texteditor", "Note")

    resources_in_root_folder = list(
        Folder.objects.filter(parent_folder_id=None)
    ) + list(Note.objects.filter(folder=None))
    resources_in_root_folder = sorted(resources_in_root_folder, key=lambda x: x.date)

    for index, resource in enumerate(resources_in_root_folder):
        resource.index = index
        resource.save()

    nested_folders = Folder.objects.all()

    for folder in nested_folders:
        resources_in_folder = list(
            Folder.objects.filter(parent_folder_id=folder.id)
        ) + list(Note.objects.filter(folder=folder))
        resources_in_folder = sorted(resources_in_folder, key=lambda x: x.date)

        for index, resource in enumerate(resources_in_folder):
            resource.index = index
            resource.save()


class Migration(migrations.Migration):

    dependencies = [
        ("texteditor", "0011_note_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="note",
            name="index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_index),
    ]
