# Generated by Django 3.2 on 2024-06-27 06:34

from django.db import migrations

from account.models import Accounts


def populate_index(apps, schema_editor):
    Folder = apps.get_model("texteditor", "Folder")
    Note = apps.get_model("texteditor", "Note")

    accounts = Accounts.objects.all()

    for account in accounts:
        resources_in_root_folder = [
            *Folder.objects.filter(parent_folder_id=None, user__id=account.id),
            *Note.objects.filter(folder=None, user__id=account.id),
        ]
        resources_in_root_folder = sorted(
            resources_in_root_folder, key=lambda x: x.name
        )

        for index, resource in enumerate(resources_in_root_folder):
            resource.index = index
            resource.save()

        nested_folders = Folder.objects.all()

        for folder in nested_folders:
            resources_in_folder = [
                *Folder.objects.filter(parent_folder_id=folder.id, user__id=account.id),
                *Note.objects.filter(folder=folder, user__id=account.id),
            ]
            resources_in_folder = sorted(resources_in_folder, key=lambda x: x.name)

            for index, resource in enumerate(resources_in_folder):
                resource.index = index
                resource.save()


class Migration(migrations.Migration):

    dependencies = [
        ("texteditor", "0012_folder_and_note_index"),
    ]

    operations = [
        migrations.RunPython(populate_index),
    ]
