# Generated by Django 3.2 on 2024-12-10 06:40

from django.db import migrations, models
import django.db.models.deletion


def populate_relationships(apps, schema_editor):
    Folder = apps.get_model("texteditor", "Folder")

    for folder in Folder.objects.all():
        if folder.parent_folder_id:
            folder.folder = Folder.objects.get(id=folder.parent_folder_id)
            folder.save()


class Migration(migrations.Migration):

    dependencies = [
        ("texteditor", "0013_populate_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="texteditor.folder",
            ),
        ),
    ]
