# Generated by Django 3.2 on 2024-12-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texteditor', '0014_create_folder_field_on_folder_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder_id',
        ),
    ]
