# Generated by Django 3.2 on 2024-12-12 08:53

from django.db import migrations


def sort_folder(user, folder, Folder, Note):
    folders = Folder.objects.filter(user=user, folder=folder).order_by("index")
    notes = Note.objects.filter(user=user, folder=folder).order_by("index")

    resources_in_folder = list(folders) + list(notes)
    sorted_resources = sorted(resources_in_folder, key=lambda resource: resource.index)

    for index, resource in enumerate(sorted_resources):
        resource.index = index
        resource.save()

        if isinstance(resource, Folder):
            sort_folder(user, resource, Folder, Note)


def reset_resource_indexes(apps, schema_editor):
    Folder = apps.get_model("texteditor", "Folder")
    Note = apps.get_model("texteditor", "Note")
    Accounts = apps.get_model("account", "Accounts")

    for account in Accounts.objects.all():
        sort_folder(account, None, Folder, Note)


class Migration(migrations.Migration):

    dependencies = [
        ("texteditor", "0015_remove_parent_folder_id_from_folder_model"),
    ]

    operations = [
        migrations.RunPython(reset_resource_indexes),
    ]
