# Generated by Django 3.2 on 2024-12-16 10:35

from django.db import migrations, models
import texteditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('texteditor', '0016_reset_resource_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='token',
            field=models.CharField(default=texteditor.models.get_token, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='token',
            field=models.CharField(default=texteditor.models.get_token, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
