# Generated by Django 3.2 on 2024-12-23 08:02

from django.db import migrations, models
import django.db.models.deletion
import texteditor.models
import texteditor.storage


def add_empty_canvases(apps, schema_editor):
    Note = apps.get_model("texteditor", "Note")
    Canvas = apps.get_model("texteditor", "Canvas")

    for note in Note.objects.all():
        note.canvas = Canvas.objects.create()
        note.save()


class Migration(migrations.Migration):
    dependencies = [
        ("texteditor", "0017_enforce_token_uniqueness"),
    ]

    operations = [
        migrations.CreateModel(
            name="Canvas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=texteditor.storage.PrivateMediaStorage,
                        upload_to=texteditor.models.note_upload_to,
                    ),
                ),
                ("background", models.CharField(default="#FBFCFF", max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name="note",
            name="canvas",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note",
                to="texteditor.canvas",
            ),
        ),
        migrations.RunPython(
            add_empty_canvases, reverse_code=migrations.RunPython.noop
        ),
    ]
