# Generated by Django 3.2 on 2024-12-30 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("texteditor", "0018_add_canvas"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="display",
            field=models.CharField(
                choices=[("text", "Text"), ("canvas", "Canvas")],
                default="text",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="canvas",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note",
                to="texteditor.canvas",
            ),
        ),
    ]
