# Generated by Django 3.2 on 2025-01-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texteditor', '0019_create_default_display_on_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='canvas',
            new_name='canvas_file',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='file',
            new_name='text_file',
        ),
    ]
