# Generated by Django 3.2 on 2023-12-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="room_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
