# Generated by Django 3.2 on 2023-12-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_accounts_room_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounts",
            name="room_name",
        ),
    ]
